policyserviceaddress: http://localhost:4242
metaserviceaddress: http://localhost:8084

skippolicyservice: true
skipmetaservice: true

spring:
  profile: dev
##########################
# JPA configuration
##########################
#Old
#spring.jpa.hibernate.ddl-auto = create-drop
#FLyWay (none: execute migrations - validate: validate migrations before execution)
#spring.jpa.hibernate.ddl-auto = none
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    #url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
##########################
# FlyWay configuration
# More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
##########################
  flyway:
    #enabled: false # To disable
    url: jdbc:h2:mem:testdb
    user: sa
    password:
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    schemas: flyway
    locations: classpath:db/migration/h2
    clean-on-validation-error: true
